#server.port = 8080
#server.servlet.context-path=/SpringBootApp
spring.mvc.view.prefix=/WEB-INF/view/
#spring.mvc.static-path-pattern=/resources/**
spring.jpa.hibernate.ddl-auto=update
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:mysql://localhost:3306/db_eta?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Nepal1989@


